{{- if or .Values.postgresql.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "postgresql" }}
  labels: {{- include "template.postgresql.labels" . | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "template.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.postgresql.env -}}
  {{- include "template.env" .Values.postgresql | indent 2 }}
  {{- end -}}
{{- end -}}
