{{- if or .Values.vault.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "vault" }}
  labels: {{- include "template.vault.labels" . | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "template.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.vault.env -}}
  {{- include "template.env" .Values.vault | indent 2 }}
  {{- end -}}
{{- end -}}
