{{- if or .Values.servicename.envCm .Values.global.envCm -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
data:
  {{- if .Values.global.envCm -}}
  {{- include "helper.env" .Values.global.envCm | indent 2 }}
  {{- end -}}
  {{- if .Values.servicename.envCm -}}
  {{- include "helper.env" .Values.servicename.envCm | indent 2 }}
  {{- end -}}
{{- end -}}
