{{- if not .Values.servicename.statefulset }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
spec:
  {{- if not .Values.servicename.autoscaling.enabled }}
  replicas: {{ .Values.servicename.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.servicename.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "servicename") | nindent 6 }}
  strategy:
    type: {{ .Values.servicename.strategy.type }}
    {{- if eq .Values.servicename.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.servicename.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.servicename.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      {{- if or .Values.servicename.podAnnotations .Values.servicename.secrets .Values.servicename.env .Values.global.env .Values.global.secrets }}
      annotations:
        {{- include "helper.checksum" (list $ "/servicename/configmap.yaml") | nindent 8 }}
        {{- include "helper.checksum" (list $ "/servicename/secret.yaml") | nindent 8 }}
        {{- if .Values.servicename.podAnnotations }}
        {{- toYaml .Values.servicename.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels: {{- include "helper.labels" (dict "root" . "componentName" "servicename") | nindent 8 }}
        {{- if .Values.servicename.podLabels }}
        {{- toYaml .Values.servicename.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.servicename.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.servicename.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (get .Values "servicename").serviceAccount.enabled }}
      serviceAccountName: {{ .Values.servicename.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "servicename") }}
      {{- end }}
      {{- if .Values.servicename.podSecurityContext }}
      securityContext: {{- toYaml .Values.servicename.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.servicename.initContainers }}
      initContainers: {{- tpl (toYaml .Values.servicename.initContainers) . | nindent 6 }}
      {{- end }}
      containers:
      - name: servicename
        {{- if .Values.servicename.securityContext }}
        securityContext: {{- toYaml .Values.servicename.securityContext | nindent 10 }}
        {{- end }}
        image: "{{ .Values.servicename.image.repository }}:{{ .Values.servicename.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.servicename.image.pullPolicy }}
        {{- if .Values.servicename.command }}
        command:
        {{- range .Values.servicename.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.servicename.args }}
        args:
        {{- range .Values.servicename.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.servicename.containerPort }}
          name: {{ .Values.servicename.containerPortName | default "http" }}
          protocol: TCP
        {{- if .Values.servicename.extraPorts }}
          {{- toYaml .Values.servicename.extraPorts | nindent 8 }}
        {{- end }}
        {{- if or .Values.servicename.envCm .Values.global.envCm .Values.servicename.envSecret .Values.global.envSecret .Values.servicename.envFrom }}
        envFrom:
        {{- if or .Values.servicename.envCm .Values.global.envCm }}
        - configMapRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
        {{- end }}
        {{- if or .Values.servicename.envSecret .Values.global.envSecret }}
        - secretRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
        {{- end }}
        {{- if .Values.servicename.envFrom }}
          {{- toYaml .Values.servicename.envFrom | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.servicename.env }}
        env: {{- include "helper.env.map-to-array" .Values.servicename.env | nindent 8 }}
        {{- end -}}
        {{- if .Values.servicename.probes.startupProbe }}
        startupProbe: {{- toYaml .Values.servicename.probes.startupProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.servicename.probes.readinessProbe }}
        readinessProbe: {{- toYaml .Values.servicename.probes.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.servicename.probes.livenessProbe }}
        livenessProbe: {{- toYaml .Values.servicename.probes.livenessProbe | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.servicename.resources | nindent 10 }}
        {{- if .Values.servicename.volumeMounts }}
        volumeMounts: {{- toYaml .Values.servicename.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.servicename.extraContainers }}
        {{- tpl (toYaml .Values.servicename.extraContainers) . | nindent 6 }}
      {{- end }}
      {{- if .Values.servicename.hostAliases }}
      hostAliases: {{- toYaml .Values.servicename.hostAliases | nindent 6 }}
      {{- end }}
      {{- if .Values.servicename.nodeSelector }}
      nodeSelector: {{- toYaml .Values.servicename.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.servicename.affinity }}
      affinity: {{- toYaml .Values.servicename.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.servicename.tolerations }}
      tolerations: {{- toYaml .Values.servicename.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.servicename.volumes }}
      volumes: {{- toYaml .Values.servicename.volumes | nindent 6 }}
      {{- end }}
{{- end }}
