apiVersion: v2
name: homarr
type: application
version: 0.2.0
appVersion: "0.15.10"
description: Customizable browser's home page to interact with your homeserver's Docker containers (e.g. Sonarr/Radarr)
home: https://homarr.dev
deprecated: true
annotations:
  artifacthub.io/changes: |
    - kind: deprecated
      description: This chart is deprecated and will be removed in a future release
keywords: []
dependencies:
- name: keycloak
  version: ">=24.3.0"
  repository: https://charts.bitnami.com/bitnami
  condition: keycloak.enabled
sources:
- https://github.com/this-is-tobi/helm-charts
- https://github.com/ajnart/homarr
maintainers:
- name: this-is-tobi
  email: this-is-tobi@proton.me
  url: https://this-is-tobi.com
