apiVersion: v2
name: dashy
type: application
version: 1.1.0
appVersion: "3.1.0"
description: A Helm chart to deploy Dashy, a self-hostable personal dashboard that includes status-checking, widgets, themes, icon packs, a UI editor etc...
home: https://dashy.to
deprecated: true
annotations:
  artifacthub.io/changes: |
    - kind: deprecated
      description: This chart is deprecated and will be removed in a future release
keywords: []
dependencies:
- name: keycloak
  version: ">=24.3.0"
  repository: https://charts.bitnami.com/bitnami
  condition: keycloak.enabled
sources:
- https://github.com/this-is-tobi/helm-charts
- https://github.com/Lissy93/dashy
maintainers:
- name: this-is-tobi
  email: this-is-tobi@proton.me
  url: https://this-is-tobi.com
