apiVersion: v2
name: cnpg-cluster
type: application
version: 1.5.3
appVersion: "1.28.0"
description: A Helm Chart to deploy easily a CNPG cluster
home: https://cloudnative-pg.io
deprecated: false
annotations:
  artifacthub.io/category: database
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - kind: changed
      description: Upgraded cloudnative-pg dependency to 0.27.0
keywords:
- postgresql
- postgres
- cnpg
- cloudnative-pg
- database
- operator
- high-availability
- backup
- replication
- kubernetes
dependencies:
- name: cloudnative-pg
  alias: cnpg-operator
  version: ">=0.23.0"
  repository: https://cloudnative-pg.github.io/charts
  condition: cnpg-operator.enabled
sources:
- https://github.com/this-is-tobi/helm-charts
- https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
maintainers:
- name: this-is-tobi
  email: this-is-tobi@proton.me
  url: https://this-is-tobi.com
