apiVersion: v2
name: backup-utils
type: application
version: 2.0.0
appVersion: "1.0.0"
description: A Helm chart for effortless deployment of backup utilities (postgresql, s3, vault, and qdrant).
deprecated: false
annotations: {}
keywords: []
dependencies: []
sources:
- https://github.com/this-is-tobi/helm-charts
- https://github.com/this-is-tobi/tools
maintainers:
- name: this-is-tobi
  email: this-is-tobi@proton.me
  url: https://this-is-tobi.com
