{{- if and .Values.imageCredentials.username .Values.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backup-utils.name" . }}-pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "backup-utils.imagePullSecret" . }}
{{- end }}
